name: ublue hwe 42
on:
  pull_request:
  merge_group:
  schedule:
    - cron: '0 4 * * *'  # 4:00-ish UTC everyday
  workflow_dispatch:

jobs:
  build:
    name: build
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      fedora_version: 42 